package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"text/template"
	"unicode"
)

type Step struct {
	Keyword    string   `json:"keyword"`
	Text       string   `json:"text"`
	Parameters []string `json:"parameters,omitempty"`
}

type Scenario struct {
	Name     string               `json:"name"`
	Steps    []Step               `json:"steps"`
	Examples []map[string]string `json:"examples,omitempty"`
}

type Feature struct {
	Name       string     `json:"name"`
	Background []Step     `json:"background,omitempty"`
	Scenarios  []Scenario `json:"scenarios"`
}

// testTemplate generates tests that load examples at runtime from JARIZZ_FEATURE_JSON
// so that gherkin-mutator mutations in the IR are observable by the tests.
const testTemplate = `// Generated by acceptance-entrypoint-generator. Do not edit.
import XCTest
@testable import JarizzCore

// IR: {{.IRPath}}
final class {{.ClassName}}: XCTestCase {
    private static let compiledIRPath = {{.IRPathLiteral}}
{{range .Scenarios}}
    // Scenario: {{.ScenarioName}}{{range .Executions}}
    func {{.TestName}}() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: {{.ScenarioIndex}}, exampleIndex: {{.ExampleIndex}})
{{range .Steps}}        {{.}}
{{end}}    }
{{end}}{{end}}}
`

type templateScenario struct {
	ScenarioName string
	Executions   []templateExecution
}

type templateExecution struct {
	TestName      string
	ScenarioIndex int
	ExampleIndex  int
	Steps         []string
}

type templateData struct {
	ClassName      string
	IRPath         string
	IRPathLiteral  string
	Scenarios      []templateScenario
}

func toIdentifier(s string) string {
	var b strings.Builder
	cap := true
	for _, r := range s {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			if cap {
				b.WriteRune(unicode.ToUpper(r))
				cap = false
			} else {
				b.WriteRune(r)
			}
		} else {
			cap = true
		}
	}
	return b.String()
}

func featureToMetadataName(featurePath string) string {
	re := regexp.MustCompile(`[^a-z0-9]+`)
	s := strings.ToLower(featurePath)
	s = re.ReplaceAllString(s, "-")
	s = strings.Trim(s, "-")
	return s + ".json"
}

func renderStep(step Step) string {
	return fmt.Sprintf("AcceptanceRuntime.run(world: &world, example: example, keyword: %q, text: %q)",
		step.Keyword, step.Text)
}

// swiftStringLiteral produces a Swift string literal from a Go string.
func swiftStringLiteral(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	return `"` + s + `"`
}

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: acceptance-entrypoint-generator <json-ir> <generated-test-output>")
		os.Exit(2)
	}
	irPath := os.Args[1]
	outDir := os.Args[2]

	data, err := os.ReadFile(irPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error reading %s: %v\n", irPath, err)
		os.Exit(1)
	}
	var feature Feature
	if err := json.Unmarshal(data, &feature); err != nil {
		fmt.Fprintf(os.Stderr, "error parsing IR: %v\n", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(outDir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "error creating output dir: %v\n", err)
		os.Exit(1)
	}

	absIRPath, _ := filepath.Abs(irPath)
	className := toIdentifier(feature.Name) + "AcceptanceTests"
	outFile := filepath.Join(outDir, className+".swift")

	var tScenarios []templateScenario
	for si, sc := range feature.Scenarios {
		var executions []templateExecution
		exampleCount := len(sc.Examples)
		if exampleCount == 0 {
			exampleCount = 1
		}
		for ei := 0; ei < exampleCount; ei++ {
			testName := fmt.Sprintf("test_%s_example%d", toIdentifier(sc.Name), ei+1)
			var steps []string
			for _, bg := range feature.Background {
				steps = append(steps, renderStep(bg))
			}
			for _, st := range sc.Steps {
				steps = append(steps, renderStep(st))
			}
			executions = append(executions, templateExecution{
				TestName:      testName,
				ScenarioIndex: si,
				ExampleIndex:  ei,
				Steps:         steps,
			})
		}
		tScenarios = append(tScenarios, templateScenario{
			ScenarioName: sc.Name,
			Executions:   executions,
		})
	}

	tmpl := template.Must(template.New("test").Parse(testTemplate))
	f, err := os.Create(outFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error creating output file: %v\n", err)
		os.Exit(1)
	}
	defer f.Close()

	if err := tmpl.Execute(f, templateData{
		ClassName:     className,
		IRPath:        absIRPath,
		IRPathLiteral: swiftStringLiteral(absIRPath),
		Scenarios:     tScenarios,
	}); err != nil {
		fmt.Fprintf(os.Stderr, "error generating: %v\n", err)
		os.Exit(1)
	}

	generatedContent, _ := os.ReadFile(outFile)
	hash := sha256.Sum256(generatedContent)
	hashStr := "sha256:" + hex.EncodeToString(hash[:])

	metaDir := filepath.Join(filepath.Dir(filepath.Clean(outDir)), "..", "build", "acceptance", "metadata")
	if err := os.MkdirAll(metaDir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "error creating metadata dir: %v\n", err)
		os.Exit(1)
	}
	metaName := featureToMetadataName(irPath)
	metaFile := filepath.Join(metaDir, metaName)

	meta := map[string]interface{}{
		"schema_version":      1,
		"feature_path":        irPath,
		"ir_path":             absIRPath,
		"implementation_hash": hashStr,
		"hash_scope":          "generated_files",
		"generated_files":     []string{outFile},
	}
	metaJSON, _ := json.MarshalIndent(meta, "", "  ")
	if err := os.WriteFile(metaFile, metaJSON, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing metadata: %v\n", err)
		os.Exit(1)
	}

	_ = sort.Sort
	fmt.Printf("generated: %s\n", outFile)
}
