// Generated by acceptance-entrypoint-generator. Do not edit.
import XCTest
@testable import JarizzCore

// IR: /Users/zoiman/DEV/Agentic/jarizz/.worktrees/refactorer/Tests/JarizzAcceptanceTests/ir/gemini_web.json
final class GeminiWebProviderAcceptanceTests: XCTestCase {
    private static let compiledIRPath = "Tests/JarizzAcceptanceTests/ir/gemini_web.json"

    // Scenario: Panel loads the Gemini web app on first show
    func test_PanelLoadsTheGeminiWebAppOnFirstShow_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 0, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is hidden")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user presses the global hotkey \"LeftShift+RightCommand+]\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the panel content URL is \"https://gemini.google.com/app\"")
    }

    // Scenario: User can complete Google sign-in inside the panel
    func test_UserCanCompleteGoogleSignInInsideThePanel_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 1, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is hidden")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the panel is visible")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the user is not signed in to Google")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user completes Google sign-in inside the panel")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the user is signed in to Google inside the panel")
    }

    // Scenario: Google authentication popup opens inside the app
    func test_GoogleAuthenticationPopupOpensInsideTheApp_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 2, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is hidden")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the panel is visible")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the user has initiated Google sign-in")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "Google authentication requires a secondary window")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the secondary window opens inside the app")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the user can complete sign-in without switching to an external browser")
    }

    // Scenario: Hiding and showing the panel does not reload the web view
    func test_HidingAndShowingThePanelDoesNotReloadTheWebView_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 3, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is hidden")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user presses the global hotkey \"LeftShift+RightCommand+]\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the user presses the global hotkey \"LeftShift+RightCommand+]\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the user presses the global hotkey \"LeftShift+RightCommand+]\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the web view navigation count is \"1\"")
    }

    // Scenario: Google session persists after the app is restarted
    func test_GoogleSessionPersistsAfterTheAppIsRestarted_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 4, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is hidden")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the user is signed in to Google inside the panel")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user quits the app")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the user launches the app")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the user presses the global hotkey \"LeftShift+RightCommand+]\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the user is signed in to Google inside the panel")
    }

    // Scenario: Panel shows an error message when the network is unavailable
    func test_PanelShowsAnErrorMessageWhenTheNetworkIsUnavailable_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 5, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is hidden")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the network is unavailable")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user presses the global hotkey \"LeftShift+RightCommand+]\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the panel displays \"No network connection — check your internet and try again\"")
    }
}
