// Generated by acceptance-entrypoint-generator. Do not edit.
import XCTest
@testable import JarizzCore

// IR: /Users/zoiman/DEV/Agentic/jarizz/.worktrees/coder/build/acceptance/ir/menubar.json
final class MenubarIconAcceptanceTests: XCTestCase {

    // Scenario: App shows menubar icon on launch
    func test_AppShowsMenubarIconOnLaunch_example1() {
        var world = AcceptanceWorld()
        let example: [String: String] = [:]
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is not running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the app launches")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "a menubar status item is visible")
    }

    // Scenario: App has no Dock icon
    func test_AppHasNoDockIcon_example1() {
        var world = AcceptanceWorld()
        let example: [String: String] = [:]
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is not running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the app launches")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the app does not appear in the Dock")
    }
}
