// Generated by acceptance-entrypoint-generator. Do not edit.
import XCTest
@testable import JarizzCore

// IR: /Users/zoiman/DEV/Agentic/jarizz/.worktrees/refactorer/build/acceptance/ir/toggle_state.json
final class PanelToggleStateAcceptanceTests: XCTestCase {
    private static let compiledIRPath = "build/acceptance/ir/toggle_state.json"

    // Scenario: Toggle state transitions between visible and hidden
    func test_ToggleStateTransitionsBetweenVisibleAndHidden_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 0, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the panel state is \"<initial>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the panel is toggled")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the panel state is \"<result>\"")
    }

    func test_ToggleStateTransitionsBetweenVisibleAndHidden_example2() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 0, exampleIndex: 1)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the panel state is \"<initial>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the panel is toggled")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the panel state is \"<result>\"")
    }
}
