// Generated by acceptance-entrypoint-generator. Do not edit.
import XCTest
@testable import JarizzCore

// IR: /Users/zoiman/DEV/Agentic/jarizz/.worktrees/architect/Tests/JarizzAcceptanceTests/ir/panel_layout.json
final class PanelLayoutAndAppearanceAcceptanceTests: XCTestCase {
    private static let compiledIRPath = "Tests/JarizzAcceptanceTests/ir/panel_layout.json"

    // Scenario: Panel appears with a fade-in animation
    func test_PanelAppearsWithAFadeInAnimation_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 0, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is hidden")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user presses the global hotkey \"LeftShift+RightCommand+]\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the panel appears with a fade-in animation")
    }

    // Scenario: Panel center aligns with the center of the screen frame containing the mouse pointer
    func test_PanelCenterAlignsWithTheCenterOfTheScreenFrameContainingTheMousePointer_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 1, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is hidden")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the mouse pointer is on a screen with frame origin \"<origin_x>\" \"<origin_y>\" and size \"<width>\" by \"<height>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user presses the global hotkey \"LeftShift+RightCommand+]\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the panel center x is \"<center_x>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel center y is \"<center_y>\"")
    }

    func test_PanelCenterAlignsWithTheCenterOfTheScreenFrameContainingTheMousePointer_example2() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 1, exampleIndex: 1)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is hidden")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the mouse pointer is on a screen with frame origin \"<origin_x>\" \"<origin_y>\" and size \"<width>\" by \"<height>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user presses the global hotkey \"LeftShift+RightCommand+]\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the panel center x is \"<center_x>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel center y is \"<center_y>\"")
    }

    // Scenario: Panel size defaults to 50 percent of the screen frame dimensions
    func test_PanelSizeDefaultsTo50PercentOfTheScreenFrameDimensions_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 2, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is hidden")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the mouse pointer is on a screen with frame size \"<width>\" by \"<height>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user presses the global hotkey \"LeftShift+RightCommand+]\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the panel width is \"<panel_width>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel height is \"<panel_height>\"")
    }

    func test_PanelSizeDefaultsTo50PercentOfTheScreenFrameDimensions_example2() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 2, exampleIndex: 1)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is hidden")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the mouse pointer is on a screen with frame size \"<width>\" by \"<height>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user presses the global hotkey \"LeftShift+RightCommand+]\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the panel width is \"<panel_width>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel height is \"<panel_height>\"")
    }

    // Scenario: Panel content area fills the panel window
    func test_PanelContentAreaFillsThePanelWindow_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 3, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is hidden")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the mouse pointer is on a screen with frame size \"<width>\" by \"<height>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user presses the global hotkey \"LeftShift+RightCommand+]\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the panel content width is \"<panel_width>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel content height is \"<panel_height>\"")
    }

    func test_PanelContentAreaFillsThePanelWindow_example2() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 3, exampleIndex: 1)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is hidden")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the mouse pointer is on a screen with frame size \"<width>\" by \"<height>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user presses the global hotkey \"LeftShift+RightCommand+]\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the panel content width is \"<panel_width>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel content height is \"<panel_height>\"")
    }
}
