// Generated by acceptance-entrypoint-generator. Do not edit.
import XCTest
@testable import JarizzCore

// IR: /Users/zoiman/DEV/Agentic/jarizz/.worktrees/coder/Tests/JarizzAcceptanceTests/ir/provider_rail.json
final class ProviderRailOverlayAcceptanceTests: XCTestCase {
    private static let compiledIRPath = "Tests/JarizzAcceptanceTests/ir/provider_rail.json"

    // Scenario: Rail shows one button per configured provider
    func test_RailShowsOneButtonPerConfiguredProvider_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 0, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is visible")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "\"<count>\" providers are configured")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the rail has \"<count>\" provider buttons")
    }

    func test_RailShowsOneButtonPerConfiguredProvider_example2() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 0, exampleIndex: 1)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is visible")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "\"<count>\" providers are configured")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the rail has \"<count>\" provider buttons")
    }

    // Scenario: Rail is not visible when no providers are configured
    func test_RailIsNotVisibleWhenNoProvidersAreConfigured_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 1, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is visible")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "no providers are configured")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the rail is not visible")
    }

    // Scenario: Rail is not visible when the panel is hidden
    func test_RailIsNotVisibleWhenThePanelIsHidden_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 2, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is visible")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the panel is hidden")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the rail is not visible")
    }

    // Scenario: The active provider button is marked active
    func test_TheActiveProviderButtonIsMarkedActive_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 3, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is visible")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "providers \"<first>\" and \"<second>\" are configured in that order")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the active provider is \"<first>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the provider button for \"<first>\" is active")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the provider button for \"<second>\" is not active")
    }

    // Scenario: Clicking a provider button switches the active provider
    func test_ClickingAProviderButtonSwitchesTheActiveProvider_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 4, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is visible")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "providers \"<first>\" and \"<second>\" are configured in that order")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the active provider is \"<first>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user clicks the provider button for \"<second>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the active provider is \"<second>\"")
    }

    // Scenario: Clicking a provider button navigates to that provider's URL
    func test_ClickingAProviderButtonNavigatesToThatProviderSURL_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 5, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is visible")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "providers \"<first>\" and \"<second>\" are configured in that order")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the active provider is \"<first>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user clicks the provider button for \"<second>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the web provider has navigated to the URL of provider \"<second>\"")
    }

    // Scenario: Clicking the already-active provider button does not navigate again
    func test_ClickingTheAlreadyActiveProviderButtonDoesNotNavigateAgain_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 6, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is visible")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "providers \"<first>\" and \"<second>\" are configured in that order")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is showing the web view for provider \"<first>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user clicks the provider button for \"<first>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the web provider navigation count for provider \"<first>\" is \"1\"")
    }

    // Scenario: Switching away from a provider via the rail and back does not reload it
    func test_SwitchingAwayFromAProviderViaTheRailAndBackDoesNotReloadIt_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 7, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is visible")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "providers \"<first>\" and \"<second>\" are configured in that order")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is showing the web view for provider \"<first>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user clicks the provider button for \"<second>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the user clicks the provider button for \"<first>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the web provider navigation count for provider \"<first>\" is \"1\"")
    }

    // Scenario: Rail collapses when the collapse control is clicked
    func test_RailCollapsesWhenTheCollapseControlIsClicked_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 8, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is visible")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the rail is expanded")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user clicks the collapse control")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the rail is collapsed")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the provider buttons are not visible")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the expand control is visible")
    }

    // Scenario: Rail expands when the expand control is clicked
    func test_RailExpandsWhenTheExpandControlIsClicked_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 9, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is visible")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the rail is collapsed")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user clicks the expand control")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the rail is expanded")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the provider buttons are visible")
    }

    // Scenario: Rail collapse state persists across app restart
    func test_RailCollapseStatePersistsAcrossAppRestart_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 10, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is visible")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the rail is \"<state>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the app is restarted")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the rail is \"<state>\"")
    }

    func test_RailCollapseStatePersistsAcrossAppRestart_example2() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 10, exampleIndex: 1)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is visible")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the rail is \"<state>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the app is restarted")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the rail is \"<state>\"")
    }

    // Scenario: Active provider button highlight follows Ctrl+Tab
    func test_ActiveProviderButtonHighlightFollowsCtrlTab_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 11, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is visible")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "providers \"Gemini\" and \"ChatGPT\" are configured in that order")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the active provider is \"Gemini\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user presses Ctrl+Tab")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the active provider is \"ChatGPT\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the provider button for \"ChatGPT\" is active")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the provider button for \"Gemini\" is not active")
    }

    // Scenario: Ctrl+Tab cycles from the provider last activated by the rail
    func test_CtrlTabCyclesFromTheProviderLastActivatedByTheRail_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 12, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is visible")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "providers \"Gemini\", \"ChatGPT\", and \"Copilot\" are configured in that order")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the active provider is \"Gemini\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user clicks the provider button for \"Copilot\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the user presses Ctrl+Tab")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the active provider is \"Gemini\"")
    }

    // Scenario: Each provider button has the provider name as its accessibility label
    func test_EachProviderButtonHasTheProviderNameAsItsAccessibilityLabel_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 13, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is visible")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "a provider with name \"<name>\" is configured")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the provider button for \"<name>\" has accessibility label \"<name>\"")
    }

    // Scenario: Rail overlay sits on top of web content without shrinking the content area
    func test_RailOverlaySitsOnTopOfWebContentWithoutShrinkingTheContentArea_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 14, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is visible")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "\"1\" providers are configured")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the rail overlay is visible on the right edge of the panel")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the web content area fills the panel window")
    }

    // Scenario: Provider buttons are vertically centered as a group on the rail
    func test_ProviderButtonsAreVerticallyCenteredAsAGroupOnTheRail_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 15, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is visible")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "\"3\" providers are configured")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the provider buttons are vertically centered as a group on the right edge of the panel")
    }
}
