// Generated by acceptance-entrypoint-generator. Do not edit.
import XCTest
@testable import JarizzCore

// IR: /Users/zoiman/DEV/Agentic/jarizz/.worktrees/coder/Tests/JarizzAcceptanceTests/ir/providers.json
final class SettingsProvidersAcceptanceTests: XCTestCase {
    private static let compiledIRPath = "Tests/JarizzAcceptanceTests/ir/providers.json"

    // Scenario: Panel shows a placeholder when no providers are configured
    func test_PanelShowsAPlaceholderWhenNoProvidersAreConfigured_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 0, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "no providers are configured")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user shows the panel")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the panel displays \"Add a provider in Settings to get started\"")
    }

    // Scenario: User adds a web provider
    func test_UserAddsAWebProvider_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 1, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the Settings window is open on the Providers tab")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user adds a provider with name \"<name>\" and URL \"<url>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the provider \"<name>\" with URL \"<url>\" is in the provider list")
    }

    // Scenario: User removes a web provider
    func test_UserRemovesAWebProvider_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 2, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the Settings window is open on the Providers tab")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "a provider with name \"<name>\" and URL \"<url>\" exists")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user removes the provider \"<name>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the provider \"<name>\" is not in the provider list")
    }

    // Scenario: User edits a web provider
    func test_UserEditsAWebProvider_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 3, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the Settings window is open on the Providers tab")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "a provider with name \"<old_name>\" and URL \"<old_url>\" exists")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user edits the provider name to \"<new_name>\" and URL to \"<new_url>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the provider \"<new_name>\" with URL \"<new_url>\" is in the provider list")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the provider \"<old_name>\" is not in the provider list")
    }

    // Scenario: User stars a provider as the default
    func test_UserStarsAProviderAsTheDefault_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 4, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the Settings window is open on the Providers tab")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "a provider with name \"<name>\" exists")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user stars the provider \"<name>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the provider \"<name>\" is starred")
    }

    // Scenario: Starring a provider removes the star from the previous default
    func test_StarringAProviderRemovesTheStarFromThePreviousDefault_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 5, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the Settings window is open on the Providers tab")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "a provider with name \"<first>\" is starred")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "a provider with name \"<second>\" exists")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user stars the provider \"<second>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the provider \"<second>\" is starred")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the provider \"<first>\" is not starred")
    }

    // Scenario: Panel loads the starred provider on show
    func test_PanelLoadsTheStarredProviderOnShow_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 6, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "a provider with name \"<name>\" and URL \"<url>\" is starred")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user shows the panel")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the web provider has navigated to \"<url>\"")
    }

    // Scenario: Panel loads the first provider when none is starred
    func test_PanelLoadsTheFirstProviderWhenNoneIsStarred_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 7, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "no provider is starred")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the first provider in the list has URL \"<url>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user shows the panel")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the web provider has navigated to \"<url>\"")
    }

    // Scenario: Provider with an invalid URL is rejected
    func test_ProviderWithAnInvalidURLIsRejected_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 8, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the Settings window is open on the Providers tab")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user tries to add a provider with name \"Test\" and URL \"<url>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the provider is not added")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the error \"Invalid URL\" is shown")
    }

    func test_ProviderWithAnInvalidURLIsRejected_example2() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 8, exampleIndex: 1)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the Settings window is open on the Providers tab")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user tries to add a provider with name \"Test\" and URL \"<url>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the provider is not added")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the error \"Invalid URL\" is shown")
    }

    // Scenario: Provider with a duplicate URL is rejected
    func test_ProviderWithADuplicateURLIsRejected_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 9, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the Settings window is open on the Providers tab")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "a provider with URL \"<url>\" already exists")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user tries to add a provider with name \"Duplicate\" and URL \"<url>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the provider is not added")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the error \"URL already in use\" is shown")
    }

    // Scenario: Provider with an empty name is rejected
    func test_ProviderWithAnEmptyNameIsRejected_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 10, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the Settings window is open on the Providers tab")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user tries to add a provider with name \"\" and URL \"https://gemini.google.com/app\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the provider is not added")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the error \"Name is required\" is shown")
    }

    // Scenario: Configured providers persist after app restart
    func test_ConfiguredProvidersPersistAfterAppRestart_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 11, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "a provider with name \"<name>\" and URL \"<url>\" has been added")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the app is restarted")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the provider \"<name>\" with URL \"<url>\" is in the provider list")
    }

    // Scenario: Starred provider persists after app restart
    func test_StarredProviderPersistsAfterAppRestart_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 12, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the provider \"<name>\" is starred")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the app is restarted")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the provider \"<name>\" is starred")
    }

    // Scenario: Adding a provider when the maximum is already configured is rejected
    func test_AddingAProviderWhenTheMaximumIsAlreadyConfiguredIsRejected_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 13, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the Settings window is open on the Providers tab")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "\"<count>\" providers are configured")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user tries to add a provider with name \"Extra\" and URL \"https://extra.example.com\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the provider is not added")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the error \"Maximum of 6 providers allowed\" is shown")
    }
}
