// Generated by acceptance-entrypoint-generator. Do not edit.
import XCTest
@testable import JarizzCore

// IR: /Users/zoiman/DEV/Agentic/jarizz/.worktrees/coder/Tests/JarizzAcceptanceTests/ir/general.json
final class SettingsGeneralAcceptanceTests: XCTestCase {
    private static let compiledIRPath = "Tests/JarizzAcceptanceTests/ir/general.json"

    // Scenario: Right-click on the menubar icon shows a context menu
    func test_RightClickOnTheMenubarIconShowsAContextMenu_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 0, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user right-clicks the menubar icon")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "a context menu appears containing \"Settings…\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the context menu contains \"Quit jarizz\"")
    }

    // Scenario: Selecting Settings from the context menu opens the Settings window
    func test_SelectingSettingsFromTheContextMenuOpensTheSettingsWindow_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 1, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user right-clicks the menubar icon")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the user selects \"Settings…\" from the context menu")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the Settings window is visible")
    }

    // Scenario: Global hotkey defaults to LeftShift+RightCommand+] on first launch
    func test_GlobalHotkeyDefaultsToLeftShiftRightCommandOnFirstLaunch_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 2, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is launching for the first time with no saved settings")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the app launches")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the global hotkey is \"LeftShift+RightCommand+]\"")
    }

    // Scenario: Panel size defaults to 50 percent on first launch
    func test_PanelSizeDefaultsTo50PercentOnFirstLaunch_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 3, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is launching for the first time with no saved settings")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the app launches")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the panel size is \"50\" percent of the screen frame")
    }

    // Scenario: Changing the global hotkey applies immediately
    func test_ChangingTheGlobalHotkeyAppliesImmediately_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 4, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user sets the global hotkey to \"<hotkey>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the global hotkey is \"<hotkey>\"")
    }

    // Scenario: Changed global hotkey persists after app restart
    func test_ChangedGlobalHotkeyPersistsAfterAppRestart_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 5, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the global hotkey has been set to \"<hotkey>\"")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the app is restarted")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the global hotkey is \"<hotkey>\"")
    }

    // Scenario: Changing the panel size applies immediately
    func test_ChangingThePanelSizeAppliesImmediately_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 6, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user sets the panel size to \"<percent>\" percent")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the panel size is \"<percent>\" percent of the screen frame")
    }

    func test_ChangingThePanelSizeAppliesImmediately_example2() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 6, exampleIndex: 1)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user sets the panel size to \"<percent>\" percent")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the panel size is \"<percent>\" percent of the screen frame")
    }

    // Scenario: A size preview overlay appears while the slider is adjusted
    func test_ASizePreviewOverlayAppearsWhileTheSliderIsAdjusted_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 7, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the Settings window is open on the General tab")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user moves the panel size slider to \"<percent>\" percent")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "a transparent overlay is shown at \"<percent>\" percent of the current screen")
    }

    func test_ASizePreviewOverlayAppearsWhileTheSliderIsAdjusted_example2() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 7, exampleIndex: 1)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the Settings window is open on the General tab")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user moves the panel size slider to \"<percent>\" percent")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "a transparent overlay is shown at \"<percent>\" percent of the current screen")
    }

    // Scenario: Panel size is constrained between 20 and 90 percent
    func test_PanelSizeIsConstrainedBetween20And90Percent_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 8, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user sets the panel size to \"<percent>\" percent")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the panel size is \"<percent>\" percent of the screen frame")
    }

    func test_PanelSizeIsConstrainedBetween20And90Percent_example2() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 8, exampleIndex: 1)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user sets the panel size to \"<percent>\" percent")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the panel size is \"<percent>\" percent of the screen frame")
    }

    // Scenario: Changed panel size persists after app restart
    func test_ChangedPanelSizePersistsAfterAppRestart_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 9, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel size has been set to \"<percent>\" percent")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the app is restarted")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the panel size is \"<percent>\" percent of the screen frame")
    }

    // Scenario: Opening Settings dismisses the main panel if it is visible
    func test_OpeningSettingsDismissesTheMainPanelIfItIsVisible_example1() {
        var world = AcceptanceWorld()
        let example = runtimeExample(compiledIRPath: Self.compiledIRPath, scenarioIndex: 10, exampleIndex: 0)
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Given", text: "the app is running")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the panel is visible")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "When", text: "the user opens Settings")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "Then", text: "the panel is hidden")
        AcceptanceRuntime.run(world: &world, example: example, keyword: "And", text: "the Settings window is visible")
    }
}
